// <auto-generated />
using System;
using InsuranceInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceInfo.API.Migrations
{
    [DbContext(typeof(ApplicantInfoContext))]
    [Migration("20240408123657_InitialDataSeed2.0")]
    partial class InitialDataSeed20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("InsuranceInfo.API.Entities.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTobaccoUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Applicant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualIncome = 1000m,
                            DateOfBirth = new DateTime(2024, 4, 8, 18, 6, 56, 447, DateTimeKind.Local).AddTicks(8386),
                            IsTobaccoUser = true
                        },
                        new
                        {
                            Id = 2,
                            AnnualIncome = 3000m,
                            DateOfBirth = new DateTime(2024, 4, 8, 18, 6, 56, 447, DateTimeKind.Local).AddTicks(8415),
                            IsTobaccoUser = false
                        },
                        new
                        {
                            Id = 3,
                            AnnualIncome = 4000m,
                            DateOfBirth = new DateTime(2024, 4, 8, 18, 6, 56, 447, DateTimeKind.Local).AddTicks(8418),
                            IsTobaccoUser = false
                        },
                        new
                        {
                            Id = 4,
                            AnnualIncome = 4000m,
                            DateOfBirth = new DateTime(2024, 4, 8, 18, 6, 56, 447, DateTimeKind.Local).AddTicks(8574),
                            IsTobaccoUser = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
