// <auto-generated />
using System;
using InsuranceInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceInfo.API.Migrations
{
    [DbContext(typeof(ApplicantInfoContext))]
    [Migration("20240412051730_latest")]
    partial class latest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("InsuranceInfo.API.Entities.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ifTobaccoUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Applicant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualIncome = 1000m,
                            DateOfBirth = new DateTime(2024, 4, 12, 10, 47, 28, 757, DateTimeKind.Local).AddTicks(2650),
                            FirstName = "Shweta",
                            LastName = "Kumari",
                            ifTobaccoUser = 0
                        },
                        new
                        {
                            Id = 2,
                            AnnualIncome = 3000m,
                            DateOfBirth = new DateTime(2024, 4, 12, 10, 47, 28, 757, DateTimeKind.Local).AddTicks(2690),
                            FirstName = "Kunal",
                            LastName = "Kumar",
                            ifTobaccoUser = 1
                        },
                        new
                        {
                            Id = 3,
                            AnnualIncome = 4000m,
                            DateOfBirth = new DateTime(2024, 4, 12, 10, 47, 28, 757, DateTimeKind.Local).AddTicks(2697),
                            FirstName = "Shivani",
                            LastName = "Kumari",
                            ifTobaccoUser = 0
                        },
                        new
                        {
                            Id = 4,
                            AnnualIncome = 4000m,
                            DateOfBirth = new DateTime(2024, 4, 12, 10, 47, 28, 757, DateTimeKind.Local).AddTicks(2701),
                            FirstName = "Shivani",
                            LastName = "Kumari",
                            ifTobaccoUser = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
